-- 코드를 입력하세요
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
from (ANIMAL_INS join ANIMAL_OUTS on ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID)
order by DATEDIFF(ANIMAL_INS.DATETIME, ANIMAL_OUTS.DATETIME)
limit 2